# Description:  Scale the radius and color of atoms as spheres by property in the B-value column.
# Source:  placeHolder

"""
cmd.do('cmd.do("bg_color white;")')
cmd.do('cmd.do("hide everything;")')
cmd.do('cmd.do("show spheres;")')
cmd.do('cmd.do("set  stick_radius = 0.1;")')
cmd.do('cmd.do("hide everything, HET;")')
cmd.do('cmd.do("show spheres, HET;")')
cmd.do('cmd.do("set sphere_quality=3;")')
cmd.do('cmd.do("show sticks, resi 1102;")')
cmd.do('cmd.do("from pymol import stored;")')
cmd.do('cmd.do("# set the stored array equal to the b−values or use your own values; ")')
cmd.do('cmd.do("stored.bb = [ ];")')
cmd.do('cmd.do("iterate all, stored.bb.append(b);")')
cmd.do('# scale the b−values;')
cmd.do('cmd.do("M = max(stored.bb);")')
cmd.do('cmd.do("scaledBB = map(lambda x: float (x/M), stored.bb);")')
cmd.do('count = 0;')
cmd.do('# set the sphere radii independently;')
cmd.do('for x in scaledBB:')
cmd.do('     cmd.set("sphere_scale", x ,"ID %s"%count)')
cmd.do('     count = count + 1')
cmd.do('cmd.do("spectrum b, selection=4gdx;")')
cmd.do('cmd.do("space cmyk;")')
cmd.do('cmd.do("set specular_intensity , 0.25;")')
"""

cmd.do('cmd.do("bg_color white;")')
cmd.do('cmd.do("hide everything;")')
cmd.do('cmd.do("show spheres;")')
cmd.do('cmd.do("set  stick_radius = 0.1;")')
cmd.do('cmd.do("hide everything, HET;")')
cmd.do('cmd.do("show spheres, HET;")')
cmd.do('cmd.do("set sphere_quality=3;")')
cmd.do('cmd.do("show sticks, resi 1102;")')
cmd.do('cmd.do("from pymol import stored;")')
cmd.do('cmd.do("# set the stored array equal to the b−values or use your own values; ")')
cmd.do('cmd.do("stored.bb = [ ];")')
cmd.do('cmd.do("iterate all, stored.bb.append(b);")')
cmd.do('# scale the b−values;')
cmd.do('cmd.do("M = max(stored.bb);")')
cmd.do('cmd.do("scaledBB = map(lambda x: float (x/M), stored.bb);")')
cmd.do('count = 0;')
cmd.do('# set the sphere radii independently;')
cmd.do('for x in scaledBB:')
cmd.do('     cmd.set("sphere_scale", x ,"ID %s"%count)')
cmd.do('     count = count + 1')
cmd.do('cmd.do("spectrum b, selection=4gdx;")')
cmd.do('cmd.do("space cmyk;")')
cmd.do('cmd.do("set specular_intensity , 0.25;")')
