# Description:  Demo of the use of the RPC server with a drug compound via the rdkit python module.
# Source:  placeHolder

"""
cmd.do('import os;')
cmd.do('import rdkit;')
cmd.do('from rdkit import Chem;')
cmd.do('from rdkit.Chem import AllChem;')
cmd.do('from rdkit.Chem import PyMol;')
cmd.do('')
cmd.do('s = PyMOL.MolViewer();')
cmd.do('mol = Chem.MolFromSmiles("${1:CCOCCn1c(C2CC[NH+](CCc3ccc(C(C)(C)C(=O)[O-])cc3)CC2)nc2ccccc21}");')
cmd.do('mol = AllChem.AddHs(mol);')
cmd.do('AllChem.EmbedMolecule(mol);')
cmd.do('AllChem.MMFFOptimizeMolecule(mol);')
cmd.do('s.ShowMol(mol, name = "${2:bilastine}", showOnly = False);')
cmd.do('s.Zoom("${2:bilastine}");')
cmd.do('s.SetDisplayStyle("${2:bilastine}", "sticks");')
cmd.do('s.GetPNG(preDelay=5);')
"""

cmd.do('import os;')
cmd.do('import rdkit;')
cmd.do('from rdkit import Chem;')
cmd.do('from rdkit.Chem import AllChem;')
cmd.do('from rdkit.Chem import PyMol;')
cmd.do('')
cmd.do('s = PyMOL.MolViewer();')
cmd.do('mol = Chem.MolFromSmiles("CCOCCn1c(C2CC[NH+](CCc3ccc(C(C)(C)C(=O)[O-])cc3)CC2)nc2ccccc21");')
cmd.do('mol = AllChem.AddHs(mol);')
cmd.do('AllChem.EmbedMolecule(mol);')
cmd.do('AllChem.MMFFOptimizeMolecule(mol);')
cmd.do('s.ShowMol(mol, name = "bilastine", showOnly = False);')
cmd.do('s.Zoom("bilastine");')
cmd.do('s.SetDisplayStyle("bilastine", "sticks");')
cmd.do('s.GetPNG(preDelay=5);')
